---
title: "rmd example 1"
output: 
  knitrBootstrap::bootstrap_document:
    highlight: xcode
    highlight.chooser: yes
    theme: default
    theme.chooser: yes
  toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r MT, include=FALSE, echo=FALSE}
#####
##### MetaboTools pipeline
#####

knitr::opts_chunk$set(echo = TRUE)

# load MT
mt.quickload()

mt_logging(console=T) 
mt_logging(console=T) 
D <- 
  # load data
  mt_files_load_metabolon(codes.makepath("Mt/sampledata.xlsx"), "OrigScale") %>%
  # timing start
  mt_logging_tic() %>% 
  
  ###
  # heading
  mt_reporting_heading("Preprocessing") %>%
  mt_reporting_heading("Part 1", lvl=2) %>%
  # sample boxplot
  mt_plots_sampleboxplot() %>%
  # missingness plot
  mt_plots_qc_missingness() %>%
  # filter metabolites with >20% missing values, then samples with >10% missing values
  mt_pre_filtermiss(metMax=0.2) %>%
  mt_pre_filtermiss(sampleMax=0.1) %>%
  # batch correction by variable BATCH_MOCK
  mt_pre_batch_median(batches = "BATCH_MOCK") %>%
  # heading
  mt_reporting_heading("Part 2", lvl=2) %>%
  # quotient normalization
  mt_pre_norm_quot() %>%
  # check if there is any correlation between normalization factors and outcomes (bad sign if so)
  mt_plots_qc_dilutionplot(comp="num1") %>%
  mt_plots_qc_dilutionplot(comp="Group") %>%
  # logging
  mt_pre_trans_log() %>%
  # KNN imputation
  mt_pre_impute_knn() %>%
  # outlier detection (univariate)
  mt_pre_outlier(method="univariate", thr=4, perc=0.5) %>%
  # final sample boxplot
  mt_plots_sampleboxplot(color=Group, plottitle = 'final') %>%
  # PCA, colored by some rowData() fields... this function shows 2 PCs
  mt_plots_PCA(color=Group, shape=BATCH_MOCK, size=NUM_MOCK) %>%
  
  ###
  mt_reporting_heading("Statistics") %>%
  # linear model, differential test on Group
  mt_stats_univ_lm(
    formula      = ~ Group, 
    samplefilter = (Group %in% c("Li_2","Li_5")),
    name         = "Li's",
    mc.cores     = 1
  ) %>%
  # add fold changes to result tables
  mt_post_addFC(statname = "Li's") %>%
  # add multiple testing correction
  mt_post_multTest(statname = "Li's", method = "BH") %>%
  # p-value histogram
  mt_plots_pvalhist() %>%
  # Volcano plot as overview of results
  mt_plots_volcano(statname     = "Li's",
                   metab_filter = p.adj < 0.1,
                   colour       = p.value < 0.05) %>%
  
  ###
  # heading
  mt_reporting_heading("All boxplots") %>%
  # boxplots
  mt_plots_boxplot(statname           = "Li's",
                   x                  = Group,
                   fill               = Group,
                   correct_confounder = ~BRADFORD_PROTEIN + BATCH_MOCK,
                   metab_filter       = p.value<0.01,
                   metab_sort         = p.value,
                   annotation         = "{sprintf('P-value: %.1e', p.value)}\nStatistic: {sprintf('%.2f', statistic)}",
                   rows               = 2,
                   cols               = 2) %>%
  # final timing
  mt_logging_toc()


```

```{r, results='asis', warning=FALSE}
#####
##### Report generation
#####
D %>% mt_reporting_generateMD()
```

